/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#121316",
        "surface-dim": "#121316",
        "surface-bright": "#38393c",
        "surface-container-lowest": "#0d0e11",
        "surface-container-low": "#1b1b1f",
        "surface-container": "#1f1f23",
        "surface-container-high": "#292a2d",
        "surface-container-highest": "#343538",
        "on-surface": "#e3e2e6",
        "on-surface-variant": "#bdc8d1",
        "inverse-surface": "#e3e2e6",
        "inverse-on-surface": "#303034",
        outline: "#87929a",
        "outline-variant": "#3e484f",
        "surface-tint": "#7bd0ff",
        primary: "#8ed5ff",
        "on-primary": "#00354a",
        "primary-container": "#38bdf8",
        "on-primary-container": "#004965",
        "inverse-primary": "#00668a",
        secondary: "#4fdbc8",
        "on-secondary": "#003731",
        "secondary-container": "#04b4a2",
        "on-secondary-container": "#003f38",
        tertiary: "#ffc174",
        "on-tertiary": "#472a00",
        "tertiary-container": "#f59e0b",
        "on-tertiary-container": "#613b00",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
}
